// ==UserScript==
// @name         SmashKarts Auto Daily Gems
// @namespace    http://tampermonkey.net/
// @version      1.1
// @description  Automatically collects daily gems every 4 hours, max 2 times per day on Smash Karts.
// @author       KartPals Team / Quartinal
// @match        https://smashkarts.io/*
// @grant        none
// @run-at       document-idle
// ==/UserScript==

(function(){"use strict";function a(){return new Date().toISOString().slice(0,10)}const o="autoGemSpin";function i(){try{return JSON.parse(localStorage.getItem(o))||{}}catch{return{}}}function l(s){localStorage.setItem(o,JSON.stringify(s))}const u=setInterval(()=>{typeof firebase<"u"&&firebase.auth().currentUser&&(clearInterval(u),f(1))},1e3);function c(s=330){const r=firebase.auth().currentUser;return r?r.getIdTokenResult().then(t=>{const e=new XMLHttpRequest;if(e.open("GET","https://us-central1-webgltest-17af1.cloudfunctions.net/getGameDataMulti",!1),e.setRequestHeader("Authorization",`Bearer ${t.token}`),e.setRequestHeader("Content-Type","application/json"),e.send(JSON.stringify({data:{clientVersion:s,dayId:null,isNewUser:!1,platformId:"webgl",region:document.querySelector('meta[name="region"]')?.textContent||"usw",seasonId:null}})),e.status!==200)return console.error("Failed to fetch game data:",e.status,e.statusText),null;const n=JSON.parse(e.responseText).data;return!n||!n.seasonId?(console.error("Invalid response data:",n),null):(globalThis.seasonId=n.seasonId,globalThis.seasonId)}):(console.error("No user is signed in."),null)}async function d(s){const r=firebase.auth().currentUser;if(!r)return console.error("No user is signed in."),alert("You need to sign in first!"),!1;try{const t=await r.getIdToken(!0),e=await fetch("https://us-central1-webgltest-17af1.cloudfunctions.net/doDailyGemsMulti",{method:"POST",headers:{authorization:`Bearer ${t}`,"content-type":"application/json"},body:JSON.stringify({data:{seasonId:await c(),spinType:s,clientVersion:330}}),mode:"cors"}),n=await e.json();return e.ok?(console.log("Daily gems awarded successfully:",n),alert(`Success: ${JSON.stringify(n)}`),!0):(console.error("Error claiming daily gems:",n.error),alert(`Error: ${n.error||"Unknown error"}`),!1)}catch(t){return console.error("Request failed:",t),alert(`Request failed: ${t.message}`),!1}}function f(s){async function r(){const t=a(),e=i();if(e[t]||(e[t]=[]),e[t].length>=2){console.log("Max daily gems spins reached for today.");return}const n=Date.now();if(e[t].length>0&&n-e[t][e[t].length-1]<4*60*60*1e3){console.log("4 hours have not passed since last spin.");return}await d(s)&&(e[t].push(n),l(e))}r(),setInterval(r,10*60*1e3)}})();
